### ISSUE TITLE
graphql报错信息如何记录logs目录文件里面？

### ISSUE THREAD

**Issue by fangjj** [supperchong/egg-apollo-server#4]
graphql报错信息如何记录logs目录文件里面？

**Comment by supperchong** [comment]
Good Question!目前formatError函数的参数里只有error,但是[apollo-server](https://github.com/apollographql/apollo-server/pull/2608)增加了一个context参数,这两天会加上,之后就可以通过ctx.logger记录日志了

**Comment by supperchong** [comment]
更新了0.2.0版本, 可以在配置文件 中设置
```js
// config/config.${env}.js 
config.graphql = {
  formatError: (error, app) => {
    app.logger.error(error);
    return error;
  },
}
```

**Comment by fangjj** [comment]
nice! 干得漂亮
