### ISSUE TITLE
使用plugin提示没有type

### ISSUE THREAD

**Issue by hnty545** [supperchong/egg-apollo-server#7]
Cannot extend type "Subscription" because it is not defined

**Comment by hnty545** [comment]
应该是npm下的0.2.0不是你最新代码，是不是没有发布

**Comment by supperchong** [comment]
感谢反馈~之前没加测试，所以没发布 ，[egg-apollo-server@0.3.0](https://www.npmjs.com/package/egg-apollo-server)已发布

**Comment by hnty545** [comment]
const defaultSchema = `
  type Query 
  type Mutation 
  type Subscription{
    "graphql对于Object必须至少设置一个field,而Subscription一般不常用,因此设置了这个默认字段"
    dummy: String
  }
  `;

这个设计在030版里没有了

**Comment by hnty545** [comment]
@supperchong
